name: Greeting from LUO YIYANG
on: push
jobs:
my-job:
name: My Job
runs-on: ubuntu-latest
steps:
- name: Print a greeting
env:
MY_VAR: Hi there! My name is
FIRST_NAME: LUO
MIDDLE_NAME: YI
LAST_NAME: YANG
run: |
echo $MY_VAR $FIRST_NAME $MIDDLE_NAME$LAST_NAME.